export const STATES = {
  GET_STATES: "GET_STATES",
  GET_STATES_PER_COMPANY: "GET_STATES_PER_COMPANY",
  SELECTED_STATE: "SELECTED_STATE",
  RESET_SELECTED_STATE: "RESET_SELECTED_STATE",
  ON_CHECK_CHANGE: "ON_CHECK_CHANGE",
  ON_INPUT_CHANGE: "ON_INPUT_CHANGE",
  ON_REMOVE_TO_DOM: "ON_REMOVE_TO_DOM",
  //update set initial state
  UPDATE_SET_INITIAL_STATE_META_DATA: "UPDATE_SET_INITIAL_STATE_META_DATA",
};
