export const FLYERS = {
  GET_ALL_FLYER_TEMPLATES: 'GET_ALL_FLYER_TEMPLATES',
  GET_ALL_FLYERS: 'GET_ALL_FLYERS',
  ON_SEARCH: 'ON_SEARCH',
  ON_DELETE: 'ON_DELETE',
  LIST_OF_CREATED_BY: 'LIST_OF_CREATED_BY',
  LISTING_FLYERS_MODAL: 'LISTING_FLYERS_MODAL',
  FLYER_TEMPLATE_SIZE: 10,
};
